### ISSUE TITLE
List index out of range when running pbs.py

### ISSUE THREAD

**Issue by NKJunhongLi** [deepmodeling/dpdispatcher#445] opened 2024-03-26 10:36 UTC
The PBS system version I am using is:

> Version: 6.1.1.1
> Commit: 22f28343b8ee83b1234479b20224353f6c2db317

I have already written the machine.json file for it.
[machine_own.json](https://github.com/deepmodeling/dpdispatcher/files/14756877/machine_own.json)
And when I am trying to run:
`dpgen init_bulk init.json machine_own.json`
there comes an error:

> Traceback (most recent call last):
>   File "/home/lijh/anaconda3/envs/deepmd/bin/dpgen", line 8, in <module>
>     sys.exit(main())
>   File "/home/lijh/anaconda3/envs/deepmd/lib/python3.10/site-packages/dpgen/main.py", line 255, in main
>     args.func(args)
>   File "/home/lijh/anaconda3/envs/deepmd/lib/python3.10/site-packages/dpgen/data/gen.py", line 1549, in gen_init_bulk
>     run_abacus_relax(jdata, mdata)
>   File "/home/lijh/anaconda3/envs/deepmd/lib/python3.10/site-packages/dpgen/data/gen.py", line 1327, in run_abacus_relax
>     submission.run_submission()
>   File "/home/lijh/anaconda3/envs/deepmd/lib/python3.10/site-packages/dpdispatcher/submission.py", line 221, in run_submission
>     self.update_submission_state()
>   File "/home/lijh/anaconda3/envs/deepmd/lib/python3.10/site-packages/dpdispatcher/submission.py", line 345, in update_submission_state
>     job.get_job_state()
>   File "/home/lijh/anaconda3/envs/deepmd/lib/python3.10/site-packages/dpdispatcher/submission.py", line 831, in get_job_state
>     job_state = self.machine.check_status(self)
>   File "/home/lijh/anaconda3/envs/deepmd/lib/python3.10/site-packages/dpdispatcher/machines/pbs.py", line 92, in check_status
>     status_word = status_line.split()[-2]
> IndexError: list index out of range
> 

The output of `qstat -x jobID` on my system is: (take another job 506995.mu01 for an example)

> <?xml version="1.0"?>
> <Data><Job><Job_Id>506995.mu01</Job_Id><Job_Name>DeePMD_example_CH4</Job_Name><Job_Owner>lijh@mu01</Job_Owner><job_state>R</job_state><queue>gold5120</queue><server>mu01</server><Checkpoint>u</Checkpoint><ctime>1711448228</ctime><Error_Path>mu01:/home/lijh/DeePMD/CH4/01.train/intra14_inter2/$PBS_JOBID.err</Error_Path><exec_host>cu13/0-27</exec_host><Hold_Types>n</Hold_Types><Join_Path>n</Join_Path><Keep_Files>n</Keep_Files><Mail_Points>a</Mail_Points><mtime>1711448229</mtime><Output_Path>mu01:/home/lijh/DeePMD/CH4/01.train/intra14_inter2/$PBS_JOBID.log</Output_Path><Priority>0</Priority><qtime>1711448228</qtime><Rerunable>True</Rerunable><Resource_List><nodes>1:ppn=28</nodes><walltime>1152:00:00</walltime><nodect>1</nodect></Resource_List><session_id>99441</session_id><Variable_List>PBS_O_QUEUE=gold5120,PBS_O_HOME=/home/lijh,PBS_O_LOGNAME=lijh,PBS_O_PATH=/home/lijh/python3/bin:/home/lijh/abacus/bin:/home/lijh/local/x86_64-pc-linux-gnu/bin:/home/lijh/local/bin:/home/lijh/anaconda3/envs/deepmd/bin:/home/lijh/python3/bin:/home/lijh/abacus/bin:/home/lijh/local/x86_64-pc-linux-gnu/bin:/home/lijh/local/bin:/home/lijh/intel/oneapi/vtune/2024.0/bin64:/home/lijh/intel/oneapi/mpi/2021.11/opt/mpi/libfabric/bin:/home/lijh/intel/oneapi/mpi/2021.11/bin:/home/lijh/intel/oneapi/mkl/2024.0/bin:/home/lijh/intel/oneapi/itac/2022.0/bin:/home/lijh/intel/oneapi/inspector/2024.0/bin64:/home/lijh/intel/oneapi/dpcpp-ct/2024.0/bin:/home/lijh/intel/oneapi/dev-utilities/2024.0/bin:/home/lijh/intel/oneapi/debugger/2024.0/opt/debugger/bin:/home/lijh/intel/oneapi/compiler/2024.0/opt/oclfpga/bin:/home/lijh/intel/oneapi/compiler/2024.0/bin:/home/lijh/intel/oneapi/advisor/2024.0/bin64:/home/lijh/anaconda3/condabin:/usr/lib64/qt-3.3/bin:/home/lijh/perl5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/maui-3.3.1/bin:/opt/torque-6.1.1.1/bin:/opt/bin:/home/lijh/.local/bin:/home/lijh/bin,PBS_O_MAIL=/var/spool/mail/lijh,PBS_O_SHELL=/bin/bash,PBS_O_LANG=en_US.UTF-8,PBS_O_WORKDIR=/home/lijh/DeePMD/CH4/01.train/intra14_inter2,PBS_O_HOST=mu01,PBS_O_SERVER=mu01</Variable_List><euser>lijh</euser><egroup>lijh</egroup><queue_type>E</queue_type><etime>1711448228</etime><submit_args>run.sh</submit_args><start_time>1711448229</start_time><Walltime><Remaining>4147188</Remaining></Walltime><start_count>1</start_count><fault_tolerant>False</fault_tolerant><job_radix>0</job_radix><submit_host>mu01</submit_host><init_work_dir>/home/lijh/DeePMD/CH4/01.train/intra14_inter2</init_work_dir><request_version>1</request_version></Job></Data>
> 

Clearly the "job state" information is not at the word[-2] of line[-2]。
I wonder how to adjust the code in "pbs.py" for fitting my PBS qstat -x output.

**Comment by njzjz** [comment] 2024-03-26 11:28
This commit is from torque: https://github.com/adaptivecomputing/torque/commit/22f28343b8ee83b1234479b20224353f6c2db317
Use `batch_type` `torque` instead of `pbs` (stands for [openpbs](https://github.com/openpbs/openpbs)).

**Comment by njzjz** [comment] 2024-03-27 07:02
I found it a duplicate of #84.

**Closed by njzjz** 2024-03-27 07:02 UTC
